import pyautogui
import langchain
from pydantic import Field,BaseModel
import os
import time
from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage
load_dotenv()
os.environ["GROQ_API_KEY"]=os.getenv("GROQ_API_KEY")

def move_coursor(answer:str):
    x=950
    y=317
    pyautogui.moveTo(x, y,5)
    pyautogui.doubleClick()
    str="pookie"
    pyautogui.hotkey('ctrl', 'a')
    # This is to remove unnecessary '}' in leetcode which is generated by auto generation of '}' 
    for char in answer:
        pyautogui.write(char, interval=0.05)
        if char == "{":
            time.sleep(0.05)
            pyautogui.press('right')
            pyautogui.press('backspace')

    

