import pyautogui
import langchain
from pydantic import Field,BaseModel
import os
import time
from dotenv import load_dotenv
from langchain.chat_models import init_chat_model
from langchain.messages import HumanMessage
load_dotenv()
os.environ["GROQ_API_KEY"]=os.getenv("GROQ_API_KEY")

def move_coursor(answer:str):
    x=1110
    y=317
    pyautogui.moveTo(x, y,5)
    pyautogui.doubleClick()
    pyautogui.hotkey('ctrl', 'a') 
    
#    To prevent unnecessary lines in the code editor
    # Splits the string into individual lines.
    # Removes leading and trailing whitespace from each line
    # Filters out empty lines (or lines that only had spaces).
    # Joins all remaining lines back together using exactly one newline.
    answer = "\n".join(line.strip() for line in answer.splitlines() if line.strip())
     # This is to remove unnecessary '}' in leetcode which is generated by auto generation of '}'
    for char in answer:
        pyautogui.write(char, interval=0.05)
        if char == "{":
            time.sleep(0.05)
            pyautogui.press('right')
            pyautogui.press('backspace')

    

